function plotAgent(X,Y,THETA,LENGTH,WIDTH)
 % Rectangle
% fill([X+LENGTH/2*cos(THETA)-WIDTH/2*sin(THETA) X+LENGTH/2*cos(THETA)+WIDTH/2*sin(THETA) X-LENGTH/2*cos(THETA)+WIDTH/2*sin(THETA) X-LENGTH/2*cos(THETA)-WIDTH/2*sin(THETA)],[Y+LENGTH/2*sin(THETA)+WIDTH/2*cos(THETA) Y+LENGTH/2*sin(THETA)-WIDTH/2*cos(THETA) Y-LENGTH/2*sin(THETA)-WIDTH/2*cos(THETA) Y-LENGTH/2*sin(THETA)+WIDTH/2*cos(THETA)],'r')
% Triangle
fill([X+LENGTH/2*cos(THETA) X-LENGTH/2*cos(THETA)+WIDTH/2*sin(THETA) X-LENGTH/2*cos(THETA)-WIDTH/2*sin(THETA)],[Y+LENGTH/2*sin(THETA) Y-LENGTH/2*sin(THETA)-WIDTH/2*cos(THETA) Y-LENGTH/2*sin(THETA)+WIDTH/2*cos(THETA)],'r')
