function plotCar(X,Y,THETA,PHI,LENGTH,WIDTH,RADIUS)
 % Rectangle
fill([X+LENGTH/2*cos(THETA)-WIDTH/2*sin(THETA) X+LENGTH/2*cos(THETA)+WIDTH/2*sin(THETA) X-LENGTH/2*cos(THETA)+WIDTH/2*sin(THETA) X-LENGTH/2*cos(THETA)-WIDTH/2*sin(THETA)],[Y+LENGTH/2*sin(THETA)+WIDTH/2*cos(THETA) Y+LENGTH/2*sin(THETA)-WIDTH/2*cos(THETA) Y-LENGTH/2*sin(THETA)-WIDTH/2*cos(THETA) Y-LENGTH/2*sin(THETA)+WIDTH/2*cos(THETA)],'r')
% Triangle
% fill([X+LENGTH/2*cos(THETA) X-LENGTH/2*cos(THETA)+WIDTH/2*sin(THETA) X-LENGTH/2*cos(THETA)-WIDTH/2*sin(THETA)],[Y+LENGTH/2*sin(THETA) Y-LENGTH/2*sin(THETA)-WIDTH/2*cos(THETA) Y-LENGTH/2*sin(THETA)+WIDTH/2*cos(THETA)],'r')
hold on
line([X-RADIUS*(cos(THETA+PHI))/2;X+LENGTH*cos(THETA)/2+RADIUS*(cos(THETA+PHI))/2],[Y-RADIUS*(sin(THETA+PHI))/2;Y+LENGTH*sin(THETA)/2+RADIUS/2*(sin(THETA+PHI))],'color','k','LineWidth',2);
